services:
  go-mei-caixa:
    container_name: go-mei-caixa
    image: go-mei-caixa-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
    - "meicaixa_postgres"
  db:
    image: postgres:latest
    container_name: meicaixa_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meicaixa-network

volumes:
  postgres_data:

networks:
  meicaixa-network:
    name: meicaixa-network